# -*- coding: utf-8 -*-
"""Colaboratory에 오신 것을 환영합니다

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/welcome.ipynb
"""

def hamster_run(n):
  a=[0] * n
  for i in range(n):
    for j in range(n):
      if(j+1)%(i+1)==0:
        a[j]=(a[j]+1)%2

  for i in range(n-1):
    a[n-1]+=a[i]
  return a[n-1]

print(hamster_run(17))
print(hamster_run(56))
print(hamster_run(33))
